experiment:
  path_output_rec_result: results/lightgcn/amazon-book/
  path_output_rec_performance: results/lightgcn/amazon-book/
  dataset: amazon-book
  data_config:
    strategy: fixed
    train_path: ../data/lightgcn/tuning/{0}/train.tsv
    validation_path: ../data/lightgcn/tuning/{0}/valid.tsv
    test_path: ../data/lightgcn/tuning/{0}/test.tsv
  binarize: True
  top_k: 50
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    LightGCN:
      meta:
        hyper_max_evals: 25
        hyper_opt_alg: tpe
        validation_metric: Recall@20
        verbose: True
        save_recs: True
      lr: [0.01,0.005,0.001,0.0005,0.0001]
      epochs: [50, 100,  200, 300, 400, 500, 1000]
      batch_size: [1024]
      factors: [8, 16, 32, 64]
      n_layers: [1, 2, 3, 4]
      l_w: [1e-05, 1e-04, 1e-03, 1e-02]
      early_stopping:
        patience: 10 # int
        monitor: Recall@20
        validation_rate: 1
        mode: auto
        verbose: True
        min_delta: 0.001
      