experiment:
  path_output_rec_result: results/with_reported_HP/lightgcn/gowalla/
  path_output_rec_performance: results/with_reported_HP/lightgcn/gowalla/
  dataset: gowalla
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/lightgcn/training/{0}/train.tsv
    test_path: ../data/lightgcn/training/{0}/test.tsv
  binarize: True
  top_k: 50
  evaluation:
    cutoffs: [10, 20]
    simple_metrics: [nDCG, Recall]
  external_models_path: ../external/models/__init__.py
  gpu: 0
  models:
    external.LightGCN:
      meta:
        save_recs: True
      lr: 0.001
      epochs: 1
      batch_size: 2048
      factors: 64
      l_w: 0.0001
      n_fold: 1
      
# python LightGCN.py --dataset gowalla --regs [1e-4] --embed_size 64 --layer_size [64,64,64] --lr 0.001 --batch_size 2048 --epoch 1000   