experiment:
  path_output_rec_result: results/with_reported_HP/ngcf/gowalla/
  path_output_rec_performance: results/with_reported_HP/ngcf/gowalla/
  dataset: gowalla
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/ngcf/training/{0}/train.tsv
    test_path: ../data/ngcf/training/{0}/test.tsv
  binarize: True
  top_k: 50
  evaluation:
    cutoffs: [10, 20]
    simple_metrics: [nDCG, Recall]
  external_models_path: ../external/models/__init__.py
  gpu: 0
  models:
    external.NGCF:
      meta:
        save_recs: True
      lr: 0.0001
      epochs: 400
      batch_size: 512
      factors: 64
      batch_size: 256
      n_layers: 1
      l_w: 0.00001
      node_dropout: 0.1
      message_dropout: 0.1
      n_fold: 1
      
# python NGCF.py --dataset gowalla --regs [1e-5] --embed_size 64 --layer_size [64,64,64] --lr 0.0001 --save_flag 1 --pretrain 0 --batch_size 1024 
# --epoch 400 --verbose 1 --node_dropout [0.1] --mess_dropout [0.1,0.1,0.1]   